/*
 * claudi ESP-Brookesia app — see header. Renders a state-reactive pet + HUD.
 */
#include "esp_brookesia_app_claudi.hpp"

#include "esp_brookesia.hpp"
#ifdef ESP_UTILS_LOG_TAG
#   undef ESP_UTILS_LOG_TAG
#endif
#define ESP_UTILS_LOG_TAG "BS:claudi"
#include "esp_lib_utils.h"

#include "esp_timer.h"

#include <cstring>

extern "C" {
#include "claudi_core.h"
#include "claudi_net.h"
}

#define APP_NAME "claudi"

using namespace esp_brookesia::gui;
using namespace esp_brookesia::systems;

namespace esp_brookesia::apps {

ClaudiApp *ClaudiApp::_instance = nullptr;

// Per-state palette + glyph for the programmatic pet. Indexed by claudi_state_t.
struct StateStyle {
    uint32_t body;   // pet body color
    const char *tag; // short label/emoji-ish
};

static StateStyle style_for(int st)
{
    switch (st) {
    case CLAUDI_STATE_IDLE:      return {0x3A7BD5, "idle"};
    case CLAUDI_STATE_BLINK:     return {0x3A7BD5, "idle"};
    case CLAUDI_STATE_HAPPY:     return {0xF2C744, "happy"};
    case CLAUDI_STATE_SLEEPY:    return {0x4A4A5A, "zzz"};
    case CLAUDI_STATE_CURIOUS:   return {0x29C7C7, "hmm?"};
    case CLAUDI_STATE_ALERT:     return {0xE8533F, "alert"};
    case CLAUDI_STATE_BORED:     return {0x6B6B7B, "bored"};
    case CLAUDI_STATE_WORKING:   return {0x3FB950, "work"};
    case CLAUDI_STATE_THINKING:  return {0x9B6DFF, "think"};
    case CLAUDI_STATE_ATTENTION: return {0xE8533F, "you!"};
    case CLAUDI_STATE_IDEA:      return {0xF2C744, "idea"};
    case CLAUDI_STATE_EXCITED:   return {0xFF8C42, "!!"};
    default:                     return {0x3A7BD5, "idle"};
    }
}

// --- Pet art: 2 frames per state, generated by tools/gen_pet_assets.py. ---
// The generated images are C files (C-linkage global symbols), so declare them
// extern "C" — otherwise the references would be mangled into this namespace.
extern "C" {
#define DECL2(s) LV_IMAGE_DECLARE(slime_##s##_0); LV_IMAGE_DECLARE(slime_##s##_1);
DECL2(idle) DECL2(blink) DECL2(happy) DECL2(sleepy) DECL2(curious) DECL2(alert)
DECL2(bored) DECL2(working) DECL2(thinking) DECL2(attention) DECL2(idea) DECL2(excited)
#undef DECL2
}

#define PETF(s) { &slime_##s##_0, &slime_##s##_1 }
// Order MUST match claudi_state_t (idle..excited).
static const lv_image_dsc_t *kPetFrames[CLAUDI_STATE_COUNT][2] = {
    PETF(idle), PETF(blink), PETF(happy), PETF(sleepy), PETF(curious), PETF(alert),
    PETF(bored), PETF(working), PETF(thinking), PETF(attention), PETF(idea), PETF(excited),
};
#undef PETF

static uint32_t now_ms(void)
{
    return (uint32_t)(esp_timer_get_time() / 1000);
}

ClaudiApp *ClaudiApp::requestInstance()
{
    if (_instance == nullptr) {
        _instance = new ClaudiApp();
    }
    return _instance;
}

// use_default_screen=true → core creates+loads a screen; we draw on lv_scr_act().
// No status/navigation bar: the pet owns the full screen.
ClaudiApp::ClaudiApp(): App(APP_NAME, nullptr, true, false, false) {}

ClaudiApp::~ClaudiApp() {}

bool ClaudiApp::run(void)
{
    ESP_UTILS_LOGI("claudi run");

    lv_obj_t *scr = lv_scr_act();
    lv_obj_set_style_bg_color(scr, lv_color_hex(0x07070C), 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);
    lv_obj_clear_flag(scr, LV_OBJ_FLAG_SCROLLABLE);

    // Pet: the slime art as a 2-frame looping animation, scaled up and centered.
    _pet = lv_animimg_create(scr);
    lv_animimg_set_src(_pet, (const void **)kPetFrames[CLAUDI_STATE_IDLE], 2);
    lv_animimg_set_duration(_pet, 700);
    lv_animimg_set_repeat_count(_pet, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(_pet);
    lv_image_set_scale(_pet, 410);   // 172 * 410/256 ≈ 275 px on the 466 panel
    lv_obj_align(_pet, LV_ALIGN_CENTER, 0, -10);

    // Top status chip.
    _status = lv_label_create(scr);
    lv_obj_align(_status, LV_ALIGN_TOP_MID, 0, 24);
    lv_obj_set_style_text_color(_status, lv_color_hex(0xE6E6F0), 0);
    lv_obj_set_style_text_font(_status, &lv_font_montserrat_24, 0);
    lv_label_set_text(_status, "claudi  •  starting");

    // Bottom transcript.
    _transcript = lv_label_create(scr);
    lv_obj_set_width(_transcript, 420);
    lv_label_set_long_mode(_transcript, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(_transcript, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_align(_transcript, LV_ALIGN_BOTTOM_MID, 0, -18);
    lv_obj_set_style_text_color(_transcript, lv_color_hex(0x9A9AB0), 0);
    lv_obj_set_style_text_font(_transcript, &lv_font_montserrat_18, 0);
    lv_label_set_text(_transcript, "");

    // Approval card (hidden until needed).
    _card = lv_obj_create(scr);
    lv_obj_set_size(_card, 380, 110);
    lv_obj_align(_card, LV_ALIGN_CENTER, 0, 120);
    lv_obj_set_style_radius(_card, 16, 0);
    lv_obj_set_style_bg_color(_card, lv_color_hex(0x2A1212), 0);
    lv_obj_set_style_border_color(_card, lv_color_hex(0xE8533F), 0);
    lv_obj_set_style_border_width(_card, 2, 0);
    lv_obj_clear_flag(_card, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(_card, LV_OBJ_FLAG_HIDDEN);

    _card_label = lv_label_create(_card);
    lv_obj_set_width(_card_label, 350);
    lv_label_set_long_mode(_card_label, LV_LABEL_LONG_WRAP);
    lv_obj_center(_card_label);
    lv_obj_set_style_text_color(_card_label, lv_color_hex(0xFFE0DA), 0);
    lv_obj_set_style_text_font(_card_label, &lv_font_montserrat_20, 0);
    lv_label_set_text(_card_label, "");

    _last_state = -1;
    _attention_since_ms = 0;

    // Refresh ~4x/sec. Recorded by the core → auto-cleaned on close.
    _timer = lv_timer_create(onTick, 250, this);

    return true;
}

bool ClaudiApp::back(void)
{
    ESP_UTILS_CHECK_FALSE_RETURN(notifyCoreClosed(), false, "notify core closed failed");
    return true;
}

void ClaudiApp::onTick(lv_timer_t *timer)
{
    ClaudiApp *self = static_cast<ClaudiApp *>(lv_timer_get_user_data(timer));
    if (self) {
        self->applyState();
    }
}

void ClaudiApp::applyState(void)
{
    claudi_snapshot_t snap;
    claudi_net_get_snapshot(&snap);
    claudi_derived_t d = claudi_derive(&snap, now_ms());

    const bool wifi = claudi_net_is_connected();
    const StateStyle st = style_for(d.effective);

    // Swap the slime animation when the effective state changes.
    if ((int)d.effective != _last_state) {
        lv_animimg_set_src(_pet, (const void **)kPetFrames[d.effective], 2);
        lv_animimg_start(_pet);
        _last_state = (int)d.effective;
    }

    // Top status chip: state · running/total · link.
    lv_label_set_text_fmt(_status, "%s  •  %d/%d  •  %s",
                          st.tag, (int)snap.running, (int)snap.total,
                          wifi ? "wifi" : "...");

    // Transcript: newest entries, newest last. Skip the "ok <tool>" PostToolUse
    // confirmations — they read as debug noise.
    char buf[CLAUDI_MAX_ENTRIES * CLAUDI_ENTRY_LEN + 1];
    buf[0] = '\0';
    size_t off = 0;
    bool first = true;
    for (size_t i = 0; i < snap.n_entries; ++i) {
        const char *e = snap.entries[i];
        if (strncmp(e, "ok ", 3) == 0) {
            continue;
        }
        int n = snprintf(buf + off, sizeof(buf) - off, "%s%s", first ? "" : "\n", e);
        if (n < 0 || (size_t)n >= sizeof(buf) - off) {
            break;
        }
        off += (size_t)n;
        first = false;
    }
    lv_label_set_text(_transcript, buf);

    // Approval card: shown whenever the human is needed (waiting / prompt).
    const bool needs_human = snap.waiting || snap.prompt.set;
    if (needs_human) {
        if (_attention_since_ms == 0) {
            _attention_since_ms = now_ms();
        }
        uint32_t elapsed_s = (now_ms() - _attention_since_ms) / 1000;
        const char *tool = snap.prompt.tool[0] ? snap.prompt.tool : "input";
        const char *hint = snap.prompt.hint[0] ? snap.prompt.hint : snap.msg;
        lv_label_set_text_fmt(_card_label, "! approve %s  (%us)\n%s",
                              tool, (unsigned)elapsed_s, hint);
        // Escalate the border after ~10s of waiting.
        lv_obj_set_style_border_color(
            _card, lv_color_hex(elapsed_s >= 10 ? 0xFF2D1A : 0xE8533F), 0);
        lv_obj_clear_flag(_card, LV_OBJ_FLAG_HIDDEN);
    } else {
        _attention_since_ms = 0;
        lv_obj_add_flag(_card, LV_OBJ_FLAG_HIDDEN);
    }
}

// Register the app so Phone::initAppFromRegistry()/installAppFromRegistry()
// pick it up automatically (same mechanism the squareline demo uses). Must be
// invoked inside the namespace with the bare class name: the macro token-pastes
// the type into an identifier, so a qualified name would not compile.
ESP_UTILS_REGISTER_PLUGIN_WITH_CONSTRUCTOR(systems::base::App, ClaudiApp, APP_NAME, []()
{
    return std::shared_ptr<ClaudiApp>(ClaudiApp::requestInstance(), [](ClaudiApp *) {});
})

} // namespace esp_brookesia::apps
